### ISSUE TITLE
Feature Request: Clean Up input

### ISSUE THREAD

**Issue by capn-cat** [ExoOmega/Smurfy-Chan-Public#1]
Where 'Manage Messages' permissions has been granted, is it possible to have the bot delete the command + link message posted by the user? This would reduce clutter and duplication of links.

Would need to take into account situations where the user has included the command as a portion of a text message - for example if the user input was:

> How about this build guys? //S http://mwo.smurfy-net.de/mechlab#i=521&l=89826ee2ab7f879ded3ccb4f2658d24442a6348d

In this case it would be inappropriate for the bot to delete _all_ of the user's message

**Comment by ExoOmega** [comment]
Due to limitations of how smurfy bot handles commands, for the command to work properly it must be in a new message on it's own.

The manage messages permission was included with adding this feature in mind. That is also why the embed included a link to the load out.

Because it's being requested, I'll bump that up higher on the priority list.

**Comment by capn-cat** [comment]
Nice work
